### PR TITLE
Update llama-cpp-python to v0.2.38

### PR DESCRIPTION
**Pull request by Smartappli**
Bump llama python in v0.2.38

### CODE REVIEW

**Comment by gaby** [comment]
We can't bump the version until https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels does a new release.

**Comment by gaby** [comment]
Related https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/issues/41

**Comment by Smartappli** [comment]
Stand by for the moment 😃

**Comment by Smartappli** [comment]
Ping @gaby

**Pull request merged**
