### PR TITLE
Add support for Neural-Chat, OpenChat, Orca 2, and OpenLLaMa v2, Starling LM

### PR DESCRIPTION
**Pull request by Smartappli**
Add Neural-Chat  7B-v3.1 
Add OpenChat 3.5-7B
Add OpenLLaMA  3B-v2, 7B-v2, 13B-v2
Add Orca-2 7B, 13B 
Add Starling-LM-7B-Alpha

### CODE REVIEW

**Comment by gaby** [comment]
@Smartappli Can the other 2 pr's be closed and consolidated into this one? #928 #927

**Comment by Smartappli** [comment]
> These two are failing:
> 
> test/healthcheck_models.py::test_model_available[TheBloke/Falcon-180B-GGUF-falcon-180b.Q4_K_M.gguf] FAILED [ 35%]
> 
> test/healthcheck_models.py::test_model_available[TheBloke/Falcon-180B-Chat-GGUF-falcon-180b-chat.Q4_K_M.gguf] FAILED [ 39%]

Falcon180B and Falcon-180B-Chat guff files are split into three parts. I don't know how to integrate them. I'm using the syntax suggested on Hugging Face but it doesn't work. If you have any ideas on how to proceed, I'd be interested :)

huggingface-cli download TheBloke/Falcon-180B-Chat-GGUF falcon-180b-chat.Q4_K_M.gguf --local-dir . --local-dir-use-symlinks False

huggingface-cli download TheBloke/Falcon-180B-GGUF falcon-180b.Q4_K_M.gguf --local-dir . --local-dir-use-symlinks False

**Comment by gaby** [comment]
> > These two are failing:
> > test/healthcheck_models.py::test_model_available[TheBloke/Falcon-180B-GGUF-falcon-180b.Q4_K_M.gguf] FAILED [ 35%]
> > test/healthcheck_models.py::test_model_available[TheBloke/Falcon-180B-Chat-GGUF-falcon-180b-chat.Q4_K_M.gguf] FAILED [ 39%]
> 
> Falcon180B and Falcon-180B-Chat guff files are split into three parts. I don't know how to integrate them. I'm using the syntax suggested on Hugging Face but it doesn't work. If you have any ideas on how to proceed, I'd be interested :)
> 
> huggingface-cli download TheBloke/Falcon-180B-Chat-GGUF falcon-180b-chat.Q4_K_M.gguf --local-dir . --local-dir-use-symlinks False
> 
> huggingface-cli download TheBloke/Falcon-180B-GGUF falcon-180b.Q4_K_M.gguf --local-dir . --local-dir-use-symlinks False

OHHH, yeah we don't support that yet. We assume 1 file per LLM. You can skip those for a future PR.

**Comment by Smartappli** [comment]
Falcon 180B and Falcon 180B-Chat Temporary deleted :)

**Comment by Smartappli** [comment]
Thanks for your help

**Pull request merged**
