### PR TITLE
Adds support for LLaMA2 in the models.json

### LINKED ISSUE #607: add llama 2 support

### PR DESCRIPTION
**Pull request by mzen17**
Small PR Adds support for Llama v2 by modifying the models.json. Uses huggingface.co/TheBloke models:

- LlamaV2 7B - q4_0 GGML model.
- LlamaV2 13B - q4_0 GGML, chat model.
- LlamaV2 70B - q4_0 GGML, chat model.

Rest of the details of the model inside the models.json.

Fixes #607 

#611 - Recently merged PR that allows support for Llama v2 70B using gqa 8

### CODE REVIEW

**Comment by gaby** [comment]
@mzen17 Can you also update the README models list

**Comment by mzen17** [comment]
Got it. I made the commit.

**Comment by gaby** [comment]
@mzen17 Thanks for the contribution

**Comment by gaby** [comment]
Fixes #607

**Pull request merged**
